### ISSUE TITLE
about highres_template_distance.vtk

### ISSUE THREAD

**Issue by xulucheng7** [ArjunNarayanan/LinFlo-Net#2]
When I was reproducing your step.
![figure1](https://github.com/ArjunNarayanan/LinFlo-Net/assets/170483066/e5055e09-29c1-47a6-91ed-d17db46ae65a)

I have copied a copy of flow_deformation.yml and made appropriate modifications. I have set the path of templat_distance_map to the highres_template_distance.vtk file provided in your code.
![figure2](https://github.com/ArjunNarayanan/LinFlo-Net/assets/170483066/6580717a-cc4c-4484-9145-688ae094fbf9)

However, the following error occurred.
![figure3](https://github.com/ArjunNarayanan/LinFlo-Net/assets/170483066/578297ac-aaec-4697-981d-81df489e5571)

I'm not sure if the path to the templat_distance_map we set is correct. If it is, can this. vtk file be directly used with the highres_template_distance.vtk file provided in your code compression package? Or do we need to generate the corresponding files ourselves through some means? I hope you can give me more guidance, thank you.

**Comment by shihe407** [comment]
same question ,how to do next/
thanks
