### ISSUE TITLE
"pretrained_linear_transform" in /config/flow_deformation.yml

### ISSUE THREAD

**Issue by shijinjin12** [ArjunNarayanan/LinFlo-Net#4]
when I change "/config/flow_deformation.yml" to run the command,
"python workflows/train_flow_with_udf.py -config /path/to/config/file”, I don't know what the path that should be filled in "pretrained_linear_transform" in the "flow_deformation.yml" file. I can't find the "pretrained folder".

**Comment by ArjunNarayanan** [comment]
Duplicate of #3 -- closing this issue and discussing there.
