### ISSUE TITLE
some questions about visualisation

### ISSUE THREAD

**Issue by shihe407** [ArjunNarayanan/LinFlo-Net#6]
Is there a visualisation method for .vti files? I ran 

> python workflows/prepare_data \
>     --image /path/to/image/folder \
>     --segmentation /path/to/segmentation/folder \
>     --output /path/to/output/folder \ \
>     ---modality ct # can be either ct or mr
>     --ext .nii.gz #

 
none of the .vti files obtained by input files extension can be viewed for useful information.

And I ran 

> python utilities/predict_udf_test_meshes.py -config /path/to/config/file 

after training and got visible meshes, the segmentation file could be opened in 3d slicer and paraview but can't see anything useful.
<img width="724" alt="Snipaste_2024-07-09_13-47-37" src="https://github.com/ArjunNarayanan/LinFlo-Net/assets/127170930/23ab4a20-d31a-4a07-8545-182c213e2071">

**Comment by ArjunNarayanan** [comment]
I usually use paraview for .vti files. The output of `prepare_data` should produce images and segmentations that you should be able to visualize. Can you verify what is going on there?

**Comment by shihe407** [comment]
Thanks, I have seen useful information after using paraview and the issue with `prepare_data` has been resolved.
